"use client";

import React, { useState } from "react";
import Image from "next/image";
import {
  Compass,
  MapPin,
  Calendar,
  Users,
  PlusCircle,
  ShieldCheck,
  Zap,
  Sparkles,
  DollarSign,
  ArrowRight,
} from "lucide-react";
import { Container } from "@/components/common/Container";
import { SectionHeader } from "@/components/common/SectionHeader";
import { cn } from "@/lib/utils";

interface ScreenTab {
  id: string;
  name: string;
  badge: string;
  icon: any;
  src: string;
  headline: string;
  description: string;
  metricLabel: string;
  metricValue: string;
}

const TABS: ScreenTab[] = [
  {
    id: "home",
    name: "Home Hub",
    badge: "Dashboard",
    icon: Compass,
    src: "/screenshots/web/home.webp",
    headline: "Active trips, countdowns, and AI credit balances in one view.",
    description:
      "Your home base on Android. See upcoming trips, view destination weather indicators, and check your monthly Reel extraction allowances.",
    metricLabel: "Active Trips Status",
    metricValue: "Live Cloud Sync",
  },
  {
    id: "places",
    name: "Trip Places",
    badge: "Map & Coordinates",
    icon: MapPin,
    src: "/screenshots/web/trip-places.webp",
    headline: "Saved places with Google verification badges & category tags.",
    description:
      "Every save from Instagram or TikTok is mapped here. Filter by cafes, viewpoints, stays, or activities with verified address cards.",
    metricLabel: "Google Places Match",
    metricValue: "100% Accurate",
  },
  {
    id: "plan",
    name: "AI Itinerary",
    badge: "Smart Route Planning",
    icon: Calendar,
    src: "/screenshots/web/plan-ai.webp",
    headline: "Distance-aware day schedules generated by pace preference.",
    description:
      "Choose relaxed, balanced, or packed. Locra clusters nearby spots so you spend less time in transit and more time enjoying the destination.",
    metricLabel: "Transit Optimization",
    metricValue: "0 Backtracking",
  },
  {
    id: "hub",
    name: "Group Hub",
    badge: "Collaboration & Split",
    icon: Users,
    src: "/screenshots/web/trip-hub.webp",
    headline: "Live group collaboration, notes, and multi-currency splitting.",
    description:
      "Invite friends to add places, vote on dinner spots, and log expenses with automatic debt minimization.",
    metricLabel: "Expense Engine",
    metricValue: "Auto Settlement",
  },
  {
    id: "create",
    name: "New Trip",
    badge: "Quick Start",
    icon: PlusCircle,
    src: "/screenshots/web/new-trip.webp",
    headline: "Set a destination, pick dates, and invite the crew in seconds.",
    description:
      "Start from scratch or let AI generate an initial trip outline based on your saved Instagram Reel collection.",
    metricLabel: "Setup Time",
    metricValue: "< 30 seconds",
  },
];

export function InteractiveDeviceExplorer() {
  const [activeTab, setActiveTab] = useState<ScreenTab>(TABS[0]);

  return (
    <section className="py-20 sm:py-32 bg-[#060608] border-y border-white/10 relative overflow-hidden">
      {/* Soft central ambient orange light */}
      <div className="ambient-orange-spot left-1/2 -translate-x-1/2 top-1/3 w-[700px] h-[500px]" />

      <Container size="xl" className="relative z-10">
        <SectionHeader
          badge="Interactive Android Showcase"
          badgeVariant="accent"
          title={
            <span className="text-white">
              Explore every screen of the <span className="hero-gradient-text">Android App.</span>
            </span>
          }
          description="Click through the five core workspaces built into the Locra AI mobile experience."
        />

        {/* Tab Selector Bar */}
        <div className="mt-12 flex flex-wrap items-center justify-center gap-2 max-w-3xl mx-auto">
          {TABS.map((tab) => {
            const Icon = tab.icon;
            const isSelected = activeTab.id === tab.id;
            return (
              <button
                key={tab.id}
                type="button"
                onClick={() => setActiveTab(tab)}
                className={cn(
                  "inline-flex items-center gap-2 rounded-full px-4 py-2 text-xs font-bold transition-all",
                  isSelected
                    ? "bg-accent text-[#140A02] accent-glow scale-105"
                    : "glass-card text-white/60 hover:text-white hover:bg-white/[0.06] border border-white/10"
                )}
              >
                <Icon className="w-3.5 h-3.5" />
                <span>{tab.name}</span>
              </button>
            );
          })}
        </div>

        {/* Interactive Phone & Narrative Box */}
        <div className="mt-14 max-w-5xl mx-auto rounded-3xl glass-strong p-6 sm:p-10 border border-white/10">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 lg:gap-14 items-center">
            {/* Left: Flagship Phone Mockup */}
            <div className="lg:col-span-5 flex justify-center relative">
              <div className="relative w-[min(290px,76vw)] sm:w-[310px]">
                {/* Android Device Frame */}
                <div className="relative rounded-[2.6rem] bg-[#050507] p-2.5 border border-white/15 shadow-2xl ring-1 ring-white/10">
                  <div className="absolute top-4 left-1/2 -translate-x-1/2 z-20 w-3.5 h-3.5 rounded-full bg-black border border-white/20" />
                  <div className="relative aspect-[320/713] overflow-hidden rounded-[2rem] bg-app-2 border border-white/[0.08]">
                    <Image
                      key={activeTab.src}
                      src={activeTab.src}
                      alt={activeTab.name}
                      fill
                      sizes="(max-width: 640px) 76vw, 310px"
                      className="object-cover object-top transition-opacity duration-300 animate-in fade-in"
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Right: Screen Details & Live Highlights */}
            <div className="lg:col-span-7 flex flex-col justify-between space-y-6">
              <div className="space-y-4">
                <div className="inline-flex items-center gap-2 rounded-full bg-accent/15 border border-accent/30 px-3 py-1 text-xs font-bold text-accent">
                  <Sparkles className="w-3.5 h-3.5" />
                  <span>{activeTab.badge}</span>
                </div>

                <h3 className="text-2xl sm:text-3xl font-extrabold text-white leading-tight">
                  {activeTab.headline}
                </h3>

                <p className="text-sm sm:text-base text-white/70 leading-relaxed font-normal">
                  {activeTab.description}
                </p>
              </div>

              {/* Verified Metric Card */}
              <div className="grid grid-cols-2 gap-4 p-4 rounded-2xl glass-inset border border-white/[0.06]">
                <div>
                  <span className="text-[11px] font-bold text-white/45 uppercase tracking-wider block">
                    {activeTab.metricLabel}
                  </span>
                  <span className="text-base sm:text-lg font-extrabold text-white mt-0.5 block">
                    {activeTab.metricValue}
                  </span>
                </div>
                <div>
                  <span className="text-[11px] font-bold text-white/45 uppercase tracking-wider block">
                    Android Native
                  </span>
                  <span className="text-base sm:text-lg font-extrabold text-accent mt-0.5 flex items-center gap-1">
                    <ShieldCheck className="w-4 h-4 text-ok" /> Kotlin &amp; Compose
                  </span>
                </div>
              </div>

              <div className="pt-2">
                <a
                  href="#download-app"
                  className="inline-flex items-center gap-2 text-xs font-bold text-accent hover:underline"
                >
                  <span>Get Locra on Google Play</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </Container>
    </section>
  );
}
